### ISSUE TITLE
GitHub 是拼错了还是不小心 

### ISSUE THREAD

**Issue by rainx** [liby/dotfiles#1]
为什么这里写的的 GitHab 不是 GitHub， 是故意的设计么？

https://github.com/liby/dotfiles/blob/437eaf35ba1e0d6304c7069bf867e0bf04c7bbb9/.config/git/config#L55

**Comment by liby** [comment]
This is a bit of personal bad taste, similar to 'GayHub', but now as an public project, I think such Easter eggs [should be reduced](https://github.com/liby/dotfiles/commit/9b90db1d101d64471f4c545e74a9174eda0b0a1b).

**Comment by liby** [comment]
This is a bit of personal bad taste, similar to 'GayHub', but now as a public project, I think such Easter eggs [should be reduced](https://github.com/liby/dotfiles/commit/9b90db1d101d64471f4c545e74a9174eda0b0a1b).
